<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' /> 
<link rel="stylesheet" href="css/bootstrap.min.css">
<link rel="stylesheet" href="css/style.css">
</head>
<body>

 <div class="navbar navbar-fixed-top"> 
   <div class="navbar-inner"> 
     <div class="container"> 
       <a class="brand" href="index.html">obigstore</a> 
       <ul class="nav">
         <li><a href="doc.html">Documentation</a></li>
         <li><a href="https://github.com/mfp/obigstore">Source code</a></li>
       </ul>
     </div> 
   </div> 
 </div> 

<div class="container">
<div class="content">


